version: "2"
services:
  app:
    container_name: reshawk-api
    restart: always
    build: .
    ports:
      - "80:3030"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
      - ./.docker/mongodb/initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_DATABASE: reshawkdb
    